### PR TITLE
Add documentation about safeMode

### PR DESCRIPTION
**Pull request by crramirez**
Please add **hacktoberfest-accepted** to the PR if you accept it.

### CODE REVIEW

**Comment by NotTheDr01ds** [comment]
Recommend adding:

> Available only in Windows 11 with WSL release 0.66.2+.

This matches the terminology used on the Systemd text earlier in the doc.

**Comment by crramirez** [comment]
Ready I added the requirements in the Notes field

**Comment by NotTheDr01ds** [comment]
I hate to be picky (but I am), and note that I'm not on the WSL team (just someone looking through the PRs), but the new text is a bit "wordy" for the notes.  Look at the other example "notes" (e.g. `guiApplications`) where they keep this short-and-sweet:

> Only available for Windows 11.

In this case, it's not just Windows 11, but also the WSL release, which is why I recommended:

> Available only in Windows 11 with WSL release 0.66.2+.

But the MS team may want to trim that down even more.  And now I'm noticing that I reversed the MS wording of "Available only" vs. "Only available", but that's my own personal nitpick with myself ;-).

Also a heads-up that, from experience, PRs aren't reviewed all that frequently by the WSL team.  Someone does get to it though.  Just want to advise "patience" ;-).

**Comment by crramirez** [comment]
Don't worry, I hope after your filter that the team won't have problems merging it.

**Comment by craigloewen-msft** [comment]
Made a small edit, but overall great change, thank you for the contribution!

**Pull request merged**
