### PR TITLE
WSL/FAQ: update URLs to current docs

### PR DESCRIPTION
**Pull request by illfated**
**Description:**
During a recent lookup in the FAQ based on a statement in a ticket in the MS ServerDocs pages, I noticed that 1 link points to an old and no longer maintained page (/previous-versions/) and some are permanently redirected from their previous site names (MSDN, TechNet) to their current pages.

This PR aims to improve the above noted issues as well as a couple of cosmetic details.

**Changes proposed:**
- [Remove-AppxPackage cmdlet] URL: 
    (/previous-versions//hh856038(v=technet.10)) 
    => (https://docs.microsoft.com/powershell/module/appx/remove-appxpackage)

- [Do not change Linux files using Windows apps and tools] URL: 
    (https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/) 
    => (https://devblogs.microsoft.com/commandline/do-not-change-linux-files-using-windows-apps-and-tools/)

- [Bash for Windows: Why it’s awesome and what it means for PowerShell] URL: 
    (https://blogs.msdn.microsoft.com/powershell/2016/04/01/bash-for-windows-why-its-awesome-and-what-it-means-for-powershell/)
    => (https://devblogs.microsoft.com/powershell/bash-for-windows-why-its-awesome-and-what-it-means-for-powershell/)

- [command-line team blog] URL: 
    (https://blogs.msdn.microsoft.com/commandline/)
    => (https://devblogs.microsoft.com/commandline/)

**Whitespace changes, formatting, cosmetic typos etc.:**
- Remove redundant blanks at end-of-line (12 occurrences)
- "filesystem" => 'file system' (3 occurrences)
- "Appdata" => 'AppData' (1 occurrence)

Ref. issue ticket https://github.com/MicrosoftDocs/windowsserverdocs/issues/5023

### CODE REVIEW

**Review by illfated — COMMENTED** [review]
- **Normal source view:** https://github.com/MicrosoftDocs/WSL/pull/1038/files
- **Hide whitespace changes:** https://github.com/MicrosoftDocs/WSL/pull/1038/files?diff=unified&w=1 (shortened review length)
- **Rich Diff view:** https://github.com/MicrosoftDocs/WSL/pull/1038/files?short_path=b0ae266 (GitHub doc reading view)

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
#sign-off

**Comment by mattwojo** [comment]
Merged. Thanks @illfated! (Sorry this took me so long to get to... so much going on with WSL!)

**Pull request merged**
