### PR TITLE
fix: New Win11 screenshot for wsl-gui-screenshot.png

### LINKED ISSUE #1324: Update screenshots to use Windows 11 screenshots for clarification
Someone thought that you could run Linux apps with GUI on Windows 10 release builds. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9766c3d7-c8ac-d361-3d34-eadaacee283c
* Version Independent ID: 03d806dd-56d9-f230-b7f8-b6f583168247
* Content: [Run Linux GUI apps with WSL](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps)
* Content Source: [WSL/tutorials/gui-apps.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/tutorials/gui-apps.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

### PR DESCRIPTION
**Pull request by Agrover112**
Replaces the Win10 insider screenshot with Win11 screenshot as the docs specify.
I noticed a user was confused because of it. 
fixes #1324

### CODE REVIEW

**Review by craigloewen-msft — APPROVED** [review]

**Comment by craigloewen-msft** [comment]
Gets an approved from me, if it looks good to you @mattwojo please feel free to merge it!

Thank you @Agrover112 for the contribution here! :)

**Comment by Agrover112** [comment]
@mattywojo

**Comment by Agrover112** [comment]
> I'm not ignoring this update --- I just need to do some checking on whether or not we can accept it. There are some very particular guidelines we try to stick to in regard to screenshots -- what icons/logos can be shown from 3rd party apps for example, just trying to do my diligence and will let you know as soon as I have a clear response.

Yea , I kinda thought this was implied a bit in the screenshots , take your time!.

**Comment by mattwojo** [comment]
Sorry for the delay -- approving and merging.  Thanks @Agrover112!

**Comment by Agrover112** [comment]
> Sorry for the delay -- approving and merging.  Thanks @Agrover112! 

Thanks ! Are there any other parts of the doc you want me to look at?

**Comment by mattwojo** [comment]
I just updated the tutorial to customize WSL command prompts with Windows Terminal and Oh My Posh if you want to take a look and let me know what you think. Here's the PR: https://github.com/MicrosoftDocs/terminal/pull/467

Thanks again!

**Comment by Agrover112** [comment]
Ah well,  i thought it was fine as it is !(PS agree with the creator as well)

**Pull request merged**
