### PR TITLE
[BrokenLinksH2] fixing broken link

### PR DESCRIPTION
**Pull request by StephenBrentPeters**
**Global effort to fix broken links**

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

### CODE REVIEW

**Comment by StephenBrentPeters** [comment]
@ShawnJackson perhaps you can merge this one?

**Comment by ShawnJackson** [comment]
@StephenBrentPeters - When you use the comment that requests a review, be sure to at-mention a content owner. I don't have permissions to merge in this repo.

**Comment by StephenBrentPeters** [comment]
@ShawnJackson That's the catch - there's no author, manager or anyone tagged in the code.  There's quite a few contributors.  Any idea how I would choose which one to contact?

**Comment by StephenBrentPeters** [comment]
@GrantMeStrength Hello John,

Global effort to fix broken links

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

**Comment by mattwojo** [comment]
@StephenBrentPeters - You can also always right-click on a docs.microsoft.com page and select "View Source". The source code should always have an ms.author field listed. In the case of this doc, it's "crloewen" (Craig Loewen), who is the PM for WSL. I can confirm and merge this page in however. Thanks for the correction.

image

**Pull request merged**
