### PR TITLE
Correct marking of IPv6 support for WSL1

### PR DESCRIPTION
**Pull request by krishnacx**
Fixes https://github.com/MicrosoftDocs/WSL/issues/1907

### CODE REVIEW

**Comment by craigloewen-msft** [comment]
IPv6 support isn't on by default yet, but it does say 'Support' so I'm inclined to show it (Or just remove this line from the table). Alternatively we could not change anything and wait until we have it on by default. What do you think @mattwoj ?

**Comment by hyanggi** [comment]
As I remembered IPv6 always worked perfectly during the WSL1 days. Are you sure it's not on by default? I can even find discussions online (from that time) talking about how to disable it.

https://askubuntu.com/questions/958876/how-to-disable-ipv6-on-windows-subsystem-for-linux

I do not understand why people these days think IPv6 did not work in WSL1.

**Comment by hyanggi** [comment]
Oh. Do you mean it's not on by default in WSL2? I thought you meant WSL1. Sorry for my misunderstanding.

**Comment by hyanggi** [comment]
IPv6 was always supported and on in WSL1. I can even find online discussions from that time talking about how to disable it.

https://askubuntu.com/questions/958876/how-to-disable-ipv6-on-windows-subsystem-for-linux

It is in WSL2 where IPv6 is not on by default.

Therefore leaving the current table as is (which states WSL1 does not support IPv6) is the worst option.

**Comment by craigloewen-msft** [comment]
merged in! Thank you both for the contribution.

**Pull request merged**
