### PR TITLE
Fix issue #1694

### PR DESCRIPTION
**Pull request by Winson-Huang**
In order to set password for MySQL root user, after installation of mysql-server, change the authentication plugin into mysql_native_password.

### CODE REVIEW

**Comment by Winson-Huang** [comment]
@microsoft-github-policy-service agree

**Comment by Winson-Huang** [comment]
@mattwojo  Please review this pull request, thank you.

**Comment by mattwojo** [comment]
@asklar - Can you confirm this fix?

**Comment by Winson-Huang** [comment]
Two months later, you havn't even review this change...

**Comment by mattwojo** [comment]
@Winson-Huang  - Thank you for this contribution to the WSL docs. We did review it, but the story was changing for WSL because of the systemd implementation. I'm not a MySQL expert, so I was trying to get help and we did a rewrite of most of this database tutorial because now that systemd is implemented in WSL, it is more in parity with any other Linux instructions. I believe that [what we have on the doc now](https://learn.microsoft.com/windows/wsl/tutorials/wsl-database#install-mysql) is more inline with this change that you proposed, so I'm closing this PR, but please take a look and if you feel that anything is incorrect or should be framed differently, please feel welcome to make an update and I'll commit to reviewing it right away. Thanks again for your contribution and my apologies that it took so long to resolve.

**Comment by mattwojo** [comment]
*I am including your addition about running the security script-- thanks for including that!

**Pull request merged**
