### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by kojomensahonums**
Replaced the word 'man' with "may" in line 481

### CODE REVIEW

**Comment by kojomensahonums** [comment]
Hi,
I want to know if the pull request will be merged or it can happen that
there won’t be merges.

Thanks,
Andrew.

**Comment by NotTheDr01ds** [comment]
@kojomensahonums I see that @benhillis did a pass through here and approved some PR's recently, but did seem to skip yours.  Personally, I'd recommend you edit the title of this one to be "Fix typo" -- It might gain more attention ;-).

**Comment by kojomensahonums** [comment]
@NotTheDr01ds Thanks for the suggestion, will make the change.

**Comment by craigloewen-msft** [comment]
Merged! Thank you for the contribution!

**Pull request merged**
