### PR TITLE
Include cmdlets dism

### PR DESCRIPTION
**Pull request by EwertonJordao**
Include Enable-WindowsOptionalFeature, dism module PowerShell I think is more clear to read cmdlet then dism command.

### CODE REVIEW

**Comment by mattwojo** [comment]
Hey @craigloewen-msft - Could you review and either approve or close? I don't know enough about the differences between these two PowerShell scripts.

**Comment by WSLUser** [comment]
They both will work. The header makes it confusing but the file changes make it obvious. They do the same thing but dism is a cmd utility that can run in powershell while the other method is powershell specific.

**Comment by EwertonJordao** [comment]
> 
> 
> They both will work. The header makes it confusing but the file changes make it obvious. They do the same thing but dism is a cmd utility that can run in powershell while the other method is powershell specific.


Yes, they do the same task. I think include that step on the documentation make it easer to undestend whats happen

**Comment by mattwojo** [comment]
My opinion is that we pick one of these scripts, including both feels like it could potentially add to confusion for new users. Let's be opinionated. If this new script makes it easier to understand what's happening, then it seems like a better option, but I'd like @craigloewen-msft to make the decision as the PM.

**Pull request closed without merging**
