### PR TITLE
docs: write out flag in `WSL/tutorials/wsl-database.md`

### LINKED ISSUE #1808: Write out `psql` command flag in PostgreSQL section of `WSL/tutorials/wsl-database.md`
### Documentation Issue

I think truncated flags like the one in `psql -c "\du"` are less informative to beginners.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-database#install-postgresql

### Suggested Improvements

I think it'd be more informative to readers if we wrote out flags, instead, like so: `psql --command="\du"`.

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #1808.

### CODE REVIEW

**Comment by zionfundz** [comment]
Thanks

**Comment by hamirmahal** [comment]
You're welcome!

**Comment by mattwojo** [comment]
Thanks @hamirmahal!

**Comment by hamirmahal** [comment]
You're welcome @mattwojo!

**Pull request merged**
