### PR TITLE
C117192: removing duplicated url inside link

### PR DESCRIPTION
**Pull request by v-maudel**
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.  
Description: invalid link is causing rendering problems on LOC pages

### CODE REVIEW

**Comment by v-maudel** [comment]
Hi @scooley, could you please help by merging this PR?
Regards.

**Comment by v-maudel** [comment]
Thanks @craigloewen-msft

**Comment by craigloewen-msft** [comment]
No problem! Thank you for submitting the change. :)

**Comment by v-nidolc** [comment]
@craigloewen-msft could you merge to the live branch, so international can hand off and get the fix? Thanks!

**Comment by craigloewen-msft** [comment]
Yup merged to live in: https://github.com/MicrosoftDocs/WSL/pull/492

(We are looking at fixing our live/master story)

**Pull request merged**
