### PR TITLE
Adding another tip that worked for many users

### PR DESCRIPTION
**Pull request by supuncbr**
WSL not responding and waiting forever issue resolving tip that worked for me and many other users

### CODE REVIEW

**Comment by Biswa96** [comment]
In most of the cases, WSL does not need a full system reboot and restarting the LxssManager or WslService service is enough for that.

**Comment by supuncbr** [comment]
yes, but  restarting the LxssManager or WslService service did not worked for me and I wasted few days troubleshooting this and only this worked

**Comment by craigloewen-msft** [comment]
Hi @supuncbr , we try not to put as a troubleshooting step for users to go into the advanced restart options for Windows, as there are some potentially destructive actions a user could take by accident on doing so (Like reformatting their operating system etc.) So we'll close this PR, thank you for the contribution!

**Comment by supuncbr** [comment]
Hi Craig,
No worries, cheers
Regards,
Supun

**Pull request closed without merging**
